[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Gabe Joseph", email = "gabe@coiled.io"},
]
dependencies = [
    "distributed>=2022.9.0",
]
requires-python = ">=3.8"
license = {text = "MIT"}
[project.optional-dependencies]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.1.3",
    "msgspec>=0.8.0",
    "filelock>=3.8.0",
]
lint = [
    "pyright>=1.1.270",
    "shed>=0.10.2",
    "flake8>=5.0.4",
]
